### ISSUE TITLE
Vagrant snapshot crashing

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#853]
I noticed that if I send my mac to sleep, my vagrant box goes into state `aborted`. Since recently (virtualbox update?) I need to `vagrant destroy -f` my box otherwise a `rake test` would fail with

```
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Command execution failed:
       vagrant snapshot go wheezy default
       STDOUT:
       Powering off machine a8263207-8b54-4d4a-89ce-7a959499b36c
       STDERR:
       There was an error while executing `VBoxManage`, a CLI used by Vagrant
       for controlling VirtualBox. The command and stderr is shown below.
       
       Command: ["controlvm", "a8263207-8b54-4d4a-89ce-7a959499b36c", "poweroff"]
       
       Stderr: VBoxManage: error: Invalid machine state: Aborted (must be Running, Paused or Stuck)
       VBoxManage: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component Console, interface IConsole, callee nsISupports
       VBoxManage: error: Context: "PowerDown(progress.asOutParam())" at line 222 of file VBoxManageControlVM.cpp
       
     # ./spec/lib/vagrant_box.rb:122:in `execute_local'
     # ./spec/lib/vagrant_box.rb:32:in `reset'
     # ./spec/spec_helper.rb:15:in `block (2 levels) in <top (required)>'
```

I also tried to manually issue `vagrant snapshot go default` resulting in a invalid VM state as above. May be upgrade `vagrant-vbox-snapshot`?
